name: vtv_go
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  chewie: ^1.14.1
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  video_player: ^2.11.1

  font_awesome_flutter: ^11.0.0
  share_plus: ^13.1.0
  scrollable_positioned_list: ^0.3.8
  provider: ^6.1.5+1
  cached_network_image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/VTVgo_app_logo.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/VTVgo_app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/channel_icons/
